VERSION 0.6

deps:
    FROM golang:1.18-alpine
    WORKDIR /services/api-service
    COPY ../calculator-service+compile/* ../calculator-service/
    COPY go.mod go.sum ./
    RUN go mod download

compile:
    FROM +deps
    COPY server.go .
    RUN go build -o server server.go

docker:
    FROM +compile
    ENTRYPOINT ["./server"]
    SAVE IMAGE k8s-go-api-service:latest k8s-go-api-service:0.1